// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.github.zack.use.projects.protobuf.proto;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Person people = 1;</code>
   */
  java.util.List<com.github.zack.use.projects.protobuf.proto.Person> 
      getPeopleList();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  com.github.zack.use.projects.protobuf.proto.Person getPeople(int index);
  /**
   * <code>repeated .Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  java.util.List<? extends com.github.zack.use.projects.protobuf.proto.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .Person people = 1;</code>
   */
  com.github.zack.use.projects.protobuf.proto.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
